export default [
  {
    id: 1,
    img: "img/Asset 60.png",
    className: "imggrid-one img-one",
    text: "Contrary to popular belief, Lorem Ipsum is not simply",
    textResponsive: "about-section imagegallerycolumn h5",
    Chaticon: "img/Asset 34.png",
    iconClass: "chaticon",
  },
  {
    id: 2,
    img: "img/Asset 62.png",
    className: "imggrid-two img-two",
    text: "Contrary to popular belief, Lorem Ipsum is not simply",
    textClass: "about-section imagegallerycolumn h5 ",
    btn: "N1,199",
    btnClassName: "about-section button ",
    Chaticon: "img/Asset 34.png",
    iconClass: "chaticon",
  },
  {
    id: 3,
    img: "img/Asset 61.png",
    className: "imggrid-three img-three",
    text: "Contrary to popular belief, Lorem Ipsum is not simply",
    textClass: "about-section imagegallerycolumn h5 ",
    btn: "N1,199",
    btnClassName: "about-section button ",
    Chaticon: "img/Asset 34.png",
    iconClass: "chaticon",
  },
  {
    id: 4,
    img: "img/Asset 63.png",
    className: "imggrid-four img-four",
    text: "Contrary to popular belief, Lorem Ipsum is not simply",
    textClass: "about-section imagegallerycolumn h5 ",
    btn: "N1,199",
    btnClassName: "about-section button ",
    Chaticon: "img/Asset 34.png",
    iconClass: "chaticon",
  },
  {
    id: 5,
    img: "img/Asset 64.png",
    className: "imggrid-five img-five",
    text: "Contrary to popular belief, Lorem Ipsum is not simply",
    textClass: "about-section imagegallerycolumn h5 ",
    btn: "N1,199",
    btnClassName: "about-section button ",
    Chaticon: "img/Asset 34.png",
    iconClass: "chaticon",
  },
  {
    id: 6,
    img: "img/Asset 65.png",
    className: "imggrid-six img-six",
    text: "Contrary to popular belief, Lorem Ipsum is not simply",
    textClass: "about-section imagegallerycolumn h5 ",
    btn: "N1,199",
    btnClassName: "about-section button ",
    Chaticon: "img/Asset 34.png",
    iconClass: "chaticon",
  },
];
